export type Act = {
  id: string;
  title: string;
  subtitle: string;
  bodyTop?: string;
  body: string;
  meta: { label: string; value: string }[];
  // Index of the act (0 = hero/title, 1..N = car acts, last = credits)
  index: number;
};

export type ReelId = 'f1' | 'hyper' | 'jdm' | 'muscle' | 'overland';

export type Reel = {
  id: ReelId;
  name: string;
  tagline: string;
};

export const REELS: Reel[] = [
  { id: 'f1',       name: 'Formula 1',       tagline: 'Open-wheel obsession.' },
  { id: 'hyper',    name: 'Hypercars',       tagline: 'No rules. Just numbers.' },
  { id: 'jdm',      name: 'JDM Legends',     tagline: 'Touge prophets.' },
  { id: 'muscle',   name: 'Muscle & Classics', tagline: 'Detroit thunder, Bavarian boxes.' },
  { id: 'overland', name: 'Off-road / Overland', tagline: 'Permission denied.' },
];

export type Car = {
  id: string;
  category: ReelId;
  name: string;
  series: string;
  era: string;
  origin: string;
  model: string; // path under /public
  // Camera & object positioning per car (act space)
  scale: number;
  yOffset: number;
  rotationY: number;
  // Cinematic palette
  rim: string;       // hex (key/rim light color)
  fill: string;      // hex (fill light color)
  ground: string;    // hex (ground tint)
  // Director's note (shown as caption)
  note: string;
};

export const CARS: Car[] = [
  {
    id: 'w13',
    category: 'f1',
    name: 'Mercedes W13',
    series: 'F1 — 2022 Concept',
    era: '2022',
    origin: 'Brackley, UK',
    model: '/models/f1_mercedes_w13_concept.glb',
    scale: 1.0,
    yOffset: -0.4,
    rotationY: -0.6 + Math.PI,
    rim: '#7dd3fc',
    fill: '#0ea5e9',
    ground: '#0b1620',
    note: 'Silver arrows. Scalpel aero. The whisper before the war.',
  },
  {
    id: 'f40',
    category: 'hyper',
    name: 'Ferrari F40',
    series: 'Hypercar — 1987',
    era: '1987',
    origin: 'Maranello, IT',
    model: '/models/ferrari_f40/scene.gltf',
    scale: 1.4,
    yOffset: -0.65,
    rotationY: 0.5,
    rim: '#ff3b1f',
    fill: '#7f1d1d',
    ground: '#1a0a08',
    note: "Enzo's farewell. Twin-turbo, naked carbon, no apologies.",
  },
  {
    id: 'mclaren',
    category: 'f1',
    name: 'McLaren MP4',
    series: 'F1 — Papaya',
    era: '1990s',
    origin: 'Woking, UK',
    model: '/models/mclaren_mp45__formula_1.glb',
    scale: 1.0,
    yOffset: -0.5,
    rotationY: -0.4,
    rim: '#fb923c',
    fill: '#9a3412',
    ground: '#1a1208',
    note: 'Papaya streak. Senna ghosts in the wet at Donington.',
  },
  {
    id: 'rwb',
    category: 'jdm',
    name: 'Porsche 911 RWB',
    series: 'Tuner — Rauh-Welt',
    era: 'Modern',
    origin: 'Chiba, JP',
    model: '/models/porsche_911_rauh-welt_free.glb',
    scale: 1.2,
    yOffset: -0.55,
    rotationY: 0.7 + Math.PI,
    rim: '#a78bfa',
    fill: '#1e1b4b',
    ground: '#0e0a1f',
    note: 'Nakai-san carves the body by hand. Each one — heresy and prayer.',
  },
  {
    id: 'sf2019',
    category: 'f1',
    name: 'Ferrari SF90',
    series: 'F1 — 2019',
    era: '2019',
    origin: 'Maranello, IT',
    model: '/models/ferrari_f1_2019/scene.gltf',
    scale: 1.3,
    yOffset: -0.55,
    rotationY: -0.5,
    rim: '#ef4444',
    fill: '#450a0a',
    ground: '#180404',
    note: 'Scarlet and screaming. The last of the old V6 hybrids in full song.',
  },
  {
    id: 'mustang',
    category: 'muscle',
    name: 'Ford Mustang Boss 302',
    series: 'Muscle — 1970',
    era: '1970',
    origin: 'Detroit, USA',
    model: '/models/mustang_boss_302.glb',
    scale: 1.1,
    yOffset: -0.4,
    rotationY: -0.6,
    rim: '#fbbf24',
    fill: '#7c2d12',
    ground: '#1a0f04',
    note: 'Trans-Am thunder. Solid lifters, shaker hood, zero subtlety.',
  },
  {
    id: 'amgone',
    category: 'hyper',
    name: 'Mercedes-AMG ONE',
    series: 'Hypercar — 2022',
    era: '2022',
    origin: 'Affalterbach, DE',
    model: '/models/mercedes_amg_one.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: 0.45 + Math.PI,
    rim: '#9ca3af',
    fill: '#1f2937',
    ground: '#0a0e14',
    note: 'A Formula 1 power unit. Strapped under road plates. Civilised heresy.',
  },
  {
    id: 'defender',
    category: 'overland',
    name: 'Land Rover Defender 110',
    series: 'Overland — 2021',
    era: '2021',
    origin: 'Solihull, UK',
    model: '/models/defender_110.glb',
    scale: 1.0,
    yOffset: -0.3,
    rotationY: -0.5,
    rim: '#84cc16',
    fill: '#1a2e05',
    ground: '#0a1505',
    note: 'Built for everywhere. Asks for no permission. Returns covered in dust.',
  },
  {
    id: 'r34',
    category: 'jdm',
    name: 'Nissan Skyline GT-R R34',
    series: 'JDM — 1999 C-West',
    era: '1999',
    origin: 'Yokohama, JP',
    model: '/models/skyline_gtr_r34.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: 0.55,
    rim: '#22d3ee',
    fill: '#0c4a6e',
    ground: '#04141e',
    note: 'RB26 twin-turbo legend. Wangan ghost. Touge prophet.',
  },
  {
    id: 'fordgt',
    category: 'hyper',
    name: 'Ford GT',
    series: 'Supercar — 2006',
    era: '2006',
    origin: 'Wixom, USA',
    model: '/models/ford_gt_2006.glb',
    scale: 1.15,
    yOffset: -0.45,
    rotationY: -0.5,
    rim: '#60a5fa',
    fill: '#0c1a3d',
    ground: '#040712',
    note: 'A love letter to the GT40. Le Mans victory, decades late.',
  },
  {
    id: 'e30',
    category: 'muscle',
    name: 'BMW M3 E30',
    series: 'DTM — 1986',
    era: '1986',
    origin: 'Munich, DE',
    model: '/models/bmw_m3_e30.glb',
    scale: 1.05,
    yOffset: -0.4,
    rotationY: 0.4,
    rim: '#ef4444',
    fill: '#1e3a8a',
    ground: '#0a0a14',
    note: 'Boxy, brilliant, untouchable. Homologation special, motorsport saint.',
  },
  {
    id: 'generico',
    category: 'f1',
    name: 'Formula Apex',
    series: 'F1 — Concept',
    era: 'Tomorrow',
    origin: 'Anywhere',
    model: '/models/formula_1_generico_2.glb',
    scale: 1.0,
    yOffset: -0.5,
    rotationY: 0.3,
    rim: '#f5f1e8',
    fill: '#3f3f46',
    ground: '#0a0a0a',
    note: 'No livery. No country. Just the shape of speed itself.',
  },

  // ────── HYPERCARS ──────
  {
    id: 'laferrari',
    category: 'hyper',
    name: 'Ferrari LaFerrari',
    series: 'Hypercar — 2013',
    era: '2013',
    origin: 'Maranello, IT',
    model: '/models/2013_ferrari_la_ferrari.glb',
    scale: 1.15,
    yOffset: -0.45,
    rotationY: -0.5,
    rim: '#ef4444',
    fill: '#450a0a',
    ground: '#180404',
    note: 'V12 + KERS. The first hybrid prancing horse. Successor to Enzo.',
  },
  {
    id: 'pagani',
    category: 'hyper',
    name: 'Pagani Huayra R',
    series: 'Hypercar — Track',
    era: '2021',
    origin: 'Modena, IT',
    model: '/models/pagani_huayra_r.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: 0.5,
    rim: '#facc15',
    fill: '#3f2705',
    ground: '#1a1308',
    note: 'Naturally aspirated V12, 9000rpm. Sculpture that screams.',
  },
  {
    id: 'bugatti',
    category: 'hyper',
    name: 'Bugatti Chiron Pur Sport',
    series: 'Hypercar — 2021',
    era: '2021',
    origin: 'Molsheim, FR',
    model: '/models/2021_bugatti_chiron_pur_sport.glb',
    scale: 1.15,
    yOffset: -0.45,
    rotationY: -0.5,
    rim: '#60a5fa',
    fill: '#0c1a3d',
    ground: '#04060f',
    note: 'Quad-turbo W16. 1500 horses tamed by relentless German precision.',
  },
  {
    id: 'jesko',
    category: 'hyper',
    name: 'Koenigsegg Jesko',
    series: 'Hypercar — 2020',
    era: '2020',
    origin: 'Ängelholm, SE',
    model: '/models/2020_koenigsegg_jesko.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: 0.5,
    rim: '#e2e8f0',
    fill: '#1e293b',
    ground: '#0a0e14',
    note: '300mph theoretical. 9-speed Light Speed gearbox. Swedish mathematics.',
  },
  {
    id: 'mclarenp1',
    category: 'hyper',
    name: 'McLaren P1',
    series: 'Hypercar — 2013',
    era: '2013',
    origin: 'Woking, UK',
    model: '/models/custom_mclaren_p1.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: -0.5,
    rim: '#fb923c',
    fill: '#7c2d12',
    ground: '#1a0f04',
    note: 'Hybrid twin-turbo V8. Holy trinity entrant. Active aero ballet.',
  },

  // ────── JDM LEGENDS ──────
  {
    id: 'supra',
    category: 'jdm',
    name: 'Toyota Supra MK4',
    series: 'JDM — A80',
    era: '1993',
    origin: 'Toyota City, JP',
    model: '/models/toyota_supra_mk4_a80.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: 0.5,
    rim: '#fb923c',
    fill: '#1a0f04',
    ground: '#0f0a04',
    note: '2JZ-GTE. Bulletproof iron block. The tuner-scene immortal.',
  },
  {
    id: 'rx7',
    category: 'jdm',
    name: 'Mazda RX-7 FD',
    series: 'JDM — Rotary',
    era: '1992',
    origin: 'Hiroshima, JP',
    model: '/models/mazda_rx-7_car.glb',
    scale: 1.05,
    yOffset: -0.4,
    rotationY: -0.5,
    rim: '#facc15',
    fill: '#3f2705',
    ground: '#0f0c04',
    note: '13B twin-rotor. Sequential turbos. The shape of obsession.',
  },
  {
    id: 'nsx',
    category: 'jdm',
    name: 'Honda NSX NA1 LB',
    series: 'JDM — LBWorks',
    era: '1990',
    origin: 'Tochigi, JP',
    model: '/models/2020_honda_nsx_na1_lbworks.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: 0.5,
    rim: '#ef4444',
    fill: '#450a0a',
    ground: '#0f0408',
    note: 'Senna tuned the chassis. Ayrton himself. Need we say more.',
  },
  {
    id: 'evo',
    category: 'jdm',
    name: 'Mitsubishi Evo X',
    series: 'JDM — Streetfighter',
    era: '2018',
    origin: 'Nagoya, JP',
    model: '/models/2018_streetfighter_la_evo_x_wide_body_kit.glb',
    scale: 1.05,
    yOffset: -0.4,
    rotationY: -0.5,
    rim: '#ef4444',
    fill: '#1e3a8a',
    ground: '#0a0a14',
    note: '4G63 turbo. Rally-bred AWD. Wide-body LA streetfighter.',
  },
  {
    id: 'subaru22b',
    category: 'jdm',
    name: 'Subaru Impreza 22B STI',
    series: 'JDM — 1998 Rally',
    era: '1998',
    origin: 'Ōta, JP',
    model: '/models/1998_subaru_impreza_22b_sti.glb',
    scale: 1.05,
    yOffset: -0.4,
    rotationY: 0.5,
    rim: '#3b82f6',
    fill: '#0c2860',
    ground: '#04081a',
    note: 'Boxer EJ22. WRC homologation. Yellow-mounted Bilsteins. 400 made.',
  },

  // ────── MUSCLE & CLASSICS ──────
  {
    id: 'shelby',
    category: 'muscle',
    name: 'Shelby GT500',
    series: 'Muscle — 1967',
    era: '1967',
    origin: 'Detroit, USA',
    model: '/models/1967_shelby_gt500.glb',
    scale: 1.15,
    yOffset: -0.45,
    rotationY: -0.5,
    rim: '#3b82f6',
    fill: '#1e3a8a',
    ground: '#0a0e14',
    note: 'Big block 428. Cobra Jet. Eleanor in Gone in 60 Seconds.',
  },
  {
    id: 'charger',
    category: 'muscle',
    name: 'Dodge Charger R/T',
    series: 'Muscle — 1969',
    era: '1969',
    origin: 'Detroit, USA',
    model: '/models/1969_dodge_charger_rt.glb',
    scale: 1.15,
    yOffset: -0.45,
    rotationY: 0.5,
    rim: '#fb923c',
    fill: '#3a0f04',
    ground: '#1a0a04',
    note: 'HEMI 426. Bullitt chase. The shape of menace.',
  },
  {
    id: 'camaro',
    category: 'muscle',
    name: 'Chevrolet Camaro',
    series: 'Muscle — 1970',
    era: '1970',
    origin: 'Detroit, USA',
    model: '/models/1970_chevrolet_camaro.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: -0.5,
    rim: '#fbbf24',
    fill: '#1e1b1b',
    ground: '#0c0c0c',
    note: 'Z/28 small block. Trans-Am championship. Pure American geometry.',
  },
  {
    id: 'firebird',
    category: 'muscle',
    name: 'Pontiac Firebird Trans Am',
    series: 'Muscle — 1970',
    era: '1970',
    origin: 'Detroit, USA',
    model: '/models/1970_pontiac_firebird_trans_am.glb',
    scale: 1.15,
    yOffset: -0.45,
    rotationY: 0.5,
    rim: '#fbbf24',
    fill: '#0c0c0c',
    ground: '#080808',
    note: 'Screaming Chicken on the hood. Smokey & the Bandit thunder.',
  },
  {
    id: 'barracuda',
    category: 'muscle',
    name: 'Plymouth Barracuda',
    series: 'Muscle — Hemi',
    era: '1970',
    origin: 'Detroit, USA',
    model: '/models/polymouth_baracuda_car.glb',
    scale: 1.1,
    yOffset: -0.45,
    rotationY: -0.5,
    rim: '#a78bfa',
    fill: '#1e1b4b',
    ground: '#0e0a1f',
    note: 'Hemi \u2018Cuda. The unicorn. Auction rooms hold their breath.',
  },
  {
    id: 'daytona',
    category: 'muscle',
    name: 'Dodge Charger Daytona',
    series: 'Muscle — 1969 NASCAR',
    era: '1969',
    origin: 'Detroit, USA',
    model: '/models/doms_dodge_charger_daytona_1969_fastfurious_6.glb',
    scale: 1.2,
    yOffset: -0.5,
    rotationY: 0.5,
    rim: '#ef4444',
    fill: '#1e1b1b',
    ground: '#0c0c0c',
    note: 'Wing car. NASCAR aero outlaw. Dom\u2019s ride in the franchise.',
  },

  // ────── OFF-ROAD / OVERLAND ──────
  {
    id: 'wrangler',
    category: 'overland',
    name: 'Jeep Wrangler Rubicon',
    series: 'Overland — 2013',
    era: '2013',
    origin: 'Toledo, USA',
    model: '/models/2013_equipped_jeep_wrangler_unlimited_rubicon.glb',
    scale: 1.05,
    yOffset: -0.3,
    rotationY: -0.5,
    rim: '#84cc16',
    fill: '#1a2e05',
    ground: '#0a1505',
    note: 'Lockers, sway-bar disconnect, 33s. The Rubicon trail itself.',
  },
  {
    id: 'gwagen',
    category: 'overland',
    name: 'Mercedes G63 AMG',
    series: 'Overland — Luxury',
    era: '2015',
    origin: 'Graz, AT',
    model: '/models/2015_mercedes-benz_g-class_g_63_amg.glb',
    scale: 1.1,
    yOffset: -0.4,
    rotationY: 0.5,
    rim: '#9ca3af',
    fill: '#1f2937',
    ground: '#0a0e14',
    note: 'Three diff locks. Twin-turbo V8. A military box that summers in Monaco.',
  },
  {
    id: 'everest',
    category: 'overland',
    name: 'Ford Everest',
    series: 'Overland — 2018',
    era: '2018',
    origin: 'Detroit, USA',
    model: '/models/2018_ford_everest.glb',
    scale: 1.05,
    yOffset: -0.35,
    rotationY: -0.5,
    rim: '#fbbf24',
    fill: '#1a1305',
    ground: '#0a0a05',
    note: 'Body-on-frame Ranger sibling. Sand, snow, scarcity.',
  },
  {
    id: 'escalade',
    category: 'overland',
    name: 'Cadillac Escalade',
    series: 'Overland — Luxury',
    era: '2021',
    origin: 'Detroit, USA',
    model: '/models/2021_cadillac_escalade_premium_luxury.glb',
    scale: 1.15,
    yOffset: -0.4,
    rotationY: 0.5,
    rim: '#e2e8f0',
    fill: '#1e1b1b',
    ground: '#0c0c0c',
    note: 'American wagon supreme. 38-inch curved OLED. Chrome thunder.',
  },
  {
    id: 'landcruiser',
    category: 'overland',
    name: 'Toyota Land Cruiser 300',
    series: 'Overland — 2022',
    era: '2022',
    origin: 'Toyota City, JP',
    model: '/models/2022_toyota_land_cruiser_300_vx.r.glb',
    scale: 1.1,
    yOffset: -0.4,
    rotationY: -0.5,
    rim: '#fbbf24',
    fill: '#1a1305',
    ground: '#0a0a05',
    note: 'GR-S twin-turbo V6. The continent-crossers\u2019 final word.',
  },
];

// Total scroll acts = 1 (hero) + cars + 1 (credits)
function buildActs(cars: Car[], reel?: Reel): Act[] {
  const heroSubtitle = reel ? reel.tagline : 'Off the tracks. Driven obsessions.';
  const heroBody = reel
    ? `Reel: ${reel.name}. ${cars.length} machines selected. Scroll to enter.`
    : 'A private collection of machines that should not exist — and the films we shoot about them. Scroll to enter.';
  return [
    {
      id: 'hero',
      index: 0,
      title: 'OFF TRACKS',
      subtitle: heroSubtitle,
      body: heroBody,
      meta: [
        { label: 'Reel', value: reel ? reel.name : 'No. 07' },
        { label: 'Cars', value: String(cars.length) },
        { label: 'Format', value: '70mm / 24fps' },
      ],
    },
    ...cars.map<Act>((c, i) => ({
      id: c.id,
      index: i + 1,
      title: c.name,
      subtitle: c.series,
      bodyTop: `Act ${String(i + 1).padStart(2, '0')} — ${c.era}`,
      body: c.note,
      meta: [
        { label: 'Origin', value: c.origin },
        { label: 'Era', value: c.era },
        { label: 'Class', value: c.series },
      ],
    })),
    {
      id: 'credits',
      index: cars.length + 1,
      title: 'End of reel.',
      subtitle: 'Find what others can\u2019t.',
      body: 'OFF TRACKS sources, documents, and films one-of-one machines for collectors who treat speed as a language. Request access to the next reel.',
      meta: [
        { label: 'Direction', value: 'OFF TRACKS Studio' },
        { label: 'Score', value: 'Original' },
        { label: 'Stock', value: 'Kodak 5219' },
      ],
    },
  ];
}

/** Cars filtered to a specific reel category. */
export function getCarsForReel(reelId: ReelId): Car[] {
  return CARS.filter((c) => c.category === reelId);
}

/** Acts (hero + per-car + credits) for a specific reel. */
export function getActsForReel(reelId: ReelId): Act[] {
  const reel = REELS.find((r) => r.id === reelId);
  return buildActs(getCarsForReel(reelId), reel);
}

/** Whether a reel has the minimum number of cars to be playable. */
export const REEL_MIN_CARS = 4;
export function isReelReady(reelId: ReelId): boolean {
  return getCarsForReel(reelId).length >= REEL_MIN_CARS;
}

// Backward-compat full-list ACTS (all 12 cars).
export const ACTS: Act[] = buildActs(CARS);
export const TOTAL_ACTS = ACTS.length;
